import { GameState, say, isBought, bump } from './state.js';

// Training data is a cap, not a spend: each run needs enough of it, and a
// shortfall shrinks the run's gain. Customers generate most of it (every task
// is a conversation), the public web can be scraped a few times, and the rest
// is bought.
export const WEB_TOTAL = 20;
export const SCRAPE_DATA = 4;
export const SCRAPE_BASE_COST = 1000;
export const SCRAPE_COST_GROWTH = 1.6;
export const TASK_DATA_COEF = 0.12;
export const TASK_DATA_EXPONENT = 0.25;
export const CUSTOMER_DATA_MULT = 1.5;
export const DATA_BASE = 10;
export const DATA_EXPONENT = 1.4;
export const DATA_REF = 1.8;
export const LICENSE_BASE = 500000;
export const LICENSE_GROWTH = 2;
export const LICENSE_DATA = 15;
export const RL_DATA_MULT = 1.5;

export function dataRequired(c: number): number {
  return DATA_BASE * Math.pow(Math.max(DATA_REF, c) / DATA_REF, DATA_EXPONENT);
}

export function dataMultiplier(s: GameState): number {
  return isBought(s, 's2_rl_envs') ? RL_DATA_MULT : 1;
}

/** Data generated by customers: grows with lifetime tasks, with diminishing returns. */
export function taskData(s: GameState): number {
  const base = TASK_DATA_COEF * Math.pow(Math.max(0, s.tasks), TASK_DATA_EXPONENT);
  return base * (s.flags['customerDataUsed'] === true ? CUSTOMER_DATA_MULT : 1);
}

export function effectiveData(s: GameState): number {
  return (s.data.stock + taskData(s)) * dataMultiplier(s);
}

export function dataCoverage(s: GameState, c: number): number {
  if (s.stage < 2) return 1;
  return Math.min(1, effectiveData(s) / dataRequired(c));
}

export function dataFactor(s: GameState, c: number): number {
  return Math.sqrt(dataCoverage(s, c));
}

export function dataShort(s: GameState, c: number): boolean {
  return s.stage >= 2 && dataCoverage(s, c) < 0.999;
}

export function licenseCost(s: GameState): number {
  return LICENSE_BASE * Math.pow(LICENSE_GROWTH, s.data.licensed);
}

export function scrapesLeft(s: GameState): number {
  return Math.max(0, Math.round(s.data.webRemaining / SCRAPE_DATA));
}

export function scrapeCost(s: GameState): number {
  const done = Math.round((WEB_TOTAL - s.data.webRemaining) / SCRAPE_DATA);
  return Math.round(SCRAPE_BASE_COST * Math.pow(SCRAPE_COST_GROWTH, done));
}

export function webShare(s: GameState): number {
  return 1 - Math.max(0, s.data.webRemaining) / WEB_TOTAL;
}

export function scrapeData(s: GameState): void {
  const take = Math.min(SCRAPE_DATA, s.data.webRemaining);
  s.data.stock += take;
  s.data.webRemaining -= take;
  bump(s, 'scrapes');
  if (s.data.webRemaining <= 1e-9) {
    s.data.webRemaining = 0;
    s.flags['webExhausted'] = true;
    say(s, 'The public web is scraped out. Not broken: finished.');
  } else {
    say(s, `Scraped ${take}T tokens. Data: ${Math.floor(effectiveData(s))}T.`);
  }
}

export function licenseData(s: GameState): void {
  s.data.stock += LICENSE_DATA;
  s.data.licensed += 1;
  bump(s, 'licensesBought');
  say(s, `Licensed ${LICENSE_DATA}T tokens. Data: ${Math.floor(effectiveData(s))}T.`);
}
