/** Browser contracts for the external reference games used by the critic. */
export {};
declare global {
  var acquiredMatter: number;
  var autoTourneyStatus: number;
  var availableMatter: number;
  var bankroll: number;
  var batteryCost: number;
  var batteryLevel: number;
  var batterySize: number;
  var boredomFlag: number;
  var clipRate: number;
  var clipmakerLevel: number;
  var clipperBoost: number;
  var clips: number;
  var creativity: number;
  var demand: number;
  var disorgFlag: number;
  var drifterCount: number;
  var entertainCost: number;
  var factoryCost: number;
  var factoryLevel: number;
  var farmCost: number;
  var farmLevel: number;
  var funds: number;
  var harvesterCost: number;
  var harvesterLevel: number;
  var honor: number;
  var humanFlag: number;
  var investLevel: number;
  var margin: number;
  var marketingLvl: number;
  var maxTrust: number;
  var megaClipperBoost: number;
  var megaClipperLevel: number;
  var memory: number;
  var milestoneFlag: number;
  var nextTrust: number;
  var operations: number;
  var probeCombat: number;
  var probeCount: number;
  var probeFac: number;
  var probeHarv: number;
  var probeHaz: number;
  var probeLaunchLevel: number;
  var probeNav: number;
  var probeRep: number;
  var probeSpeed: number;
  var probeTrust: number;
  var probeUsedTrust: number;
  var probeWire: number;
  var probesLostCombat: number;
  var probesLostDrift: number;
  var probesLostHaz: number;
  var processors: number;
  var spaceFlag: number;
  var standardOps: number;
  var storedPower: number;
  var swarmGifts: number;
  var tempOps: number;
  var ticks: number;
  var tourneyInProg: number;
  var trust: number;
  var unsoldClips: number;
  var unusedClips: number;
  var wire: number;
  var wireBuyerStatus: number;
  var wireCost: number;
  var wireDroneCost: number;
  var wireDroneLevel: number;
  var wirePurchase: number;
  var wireSupply: number;
  var yomi: number;
  function addMem(): void;
  function addProc(): void;
  var project127: { flag: number };
  var project219: { flag: number };
  var project35: { flag: number };
  var project45: { flag: number };
  var project70: { flag: number };
  var projects: { flag: number }[];
  var activeProjects: unknown[];
  interface Window {
    save: () => void;
    $SM: { get: (key: string, fallback?: unknown) => any };
    Engine: {
      activeModule?: { name: string };
      options?: { state?: unknown };
      saveGame: () => void;
      loadGame: (...args: unknown[]) => void;
    };
    State: Record<string, any>;
    __clickAcc: number;
    __sp: { grow: number; sells: number; lastMove: number; prev: number };
    __advance: (milliseconds: number) => number;
    __critic: Record<string, any>;
    __harness: Record<string, any>;
    __harnessSpec: Record<string, any>;
    __harnessMetrics: () => Record<string, any>;
    __harnessFingerprint: () => string;
  }
}
